### ISSUE TITLE
canta works bad with Save & restart button

### ISSUE THREAD

**Issue by glixx** [spiderbit/canta#12]
canta often falls when restarting or interface shows partially

**Comment by glixx** [comment]
**\* glibc detected **\* python: free(): invalid next size (normal): 0x0973be60 ***
======= Backtrace: =========
/lib/i686/libc.so.6(+0x6cbe2)[0xb7493be2]
/usr/lib/dri/nouveau_dri.so(+0x1090cb)[0xb5b220cb]
/usr/lib/dri/nouveau_dri.so(+0x16e498)[0xb5b87498]
/usr/lib/dri/nouveau_dri.so(+0x10d433)[0xb5b26433]
/usr/lib/dri/nouveau_dri.so(+0x10e81d)[0xb5b2781d]
/usr/lib/dri/nouveau_dri.so(+0xd6129)[0xb5aef129]
/usr/lib/dri/nouveau_dri.so(+0x185292)[0xb5b9e292]
/usr/lib/dri/nouveau_dri.so(+0xc3fdb)[0xb5adcfdb]
/usr/lib/dri/nouveau_dri.so(+0x1e0a9)[0xb5a370a9]
/usr/lib/dri/nouveau_dri.so(+0x19f1a)[0xb5a32f1a]
/usr/lib/libGL.so.1(+0x43a6a)[0xb6c05a6a]
/usr/lib/libGL.so.1(glXDestroyContext+0x102)[0xb6bdc942]
/usr/lib/libSDL-1.2.so.0(+0x5f704)[0xb6e6b704]
/usr/lib/libSDL-1.2.so.0(+0x69570)[0xb6e75570]
/usr/lib/libSDL-1.2.so.0(SDL_VideoQuit+0x5b)[0xb6e52b1b]
/usr/lib/libSDL-1.2.so.0(SDL_QuitSubSystem+0x54)[0xb6e11fa4]
/usr/lib/libSDL-1.2.so.0(SDL_Quit+0x1b)[0xb6e1205b]
/usr/lib/python2.7/site-packages/soya/_soya.so(+0xc1a1f)[0xb6ff9a1f]
/usr/lib/libpython2.7.so.1.0(PyCFunction_Call+0x14d)[0xb7627c7d]
/usr/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x4f25)[0xb7686a85]
/usr/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x87c)[0xb768871c]
/usr/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x4cc3)[0xb7686823]
/usr/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x5d94)[0xb76878f4]
/usr/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x5d94)[0xb76878f4]
/usr/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x87c)[0xb768871c]
/usr/lib/libpython2.7.so.1.0(+0x537bc)[0xb76127bc]
/usr/lib/libpython2.7.so.1.0(PyObject_Call+0x64)[0xb75eb584]
/usr/lib/libpython2.7.so.1.0(+0x3bf70)[0xb75faf70]
/usr/lib/libpython2.7.so.1.0(PyObject_Call+0x64)[0xb75eb584]
/usr/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x39e2)[0xb7685542]
/usr/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x5d94)[0xb76878f4]
/usr/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x5d94)[0xb76878f4]
/usr/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x5d94)[0xb76878f4]
/usr/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x5d94)[0xb76878f4]
/usr/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x87c)[0xb768871c]
/usr/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x4cc3)[0xb7686823]
/usr/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x87c)[0xb768871c]
/usr/lib/libpython2.7.so.1.0(+0x537bc)[0xb76127bc]
/usr/lib/libpython2.7.so.1.0(PyObject_Call+0x64)[0xb75eb584]
/usr/lib/libpython2.7.so.1.0(+0x3bf70)[0xb75faf70]
/usr/lib/libpython2.7.so.1.0(PyObject_Call+0x64)[0xb75eb584]
/usr/lib/libpython2.7.so.1.0(PyEval_CallObjectWithKeywords+0x5b)[0xb768153b]
/usr/lib/libpython2.7.so.1.0(PyObject_CallObject+0x2b)[0xb75eb51b]
/usr/lib/python2.7/site-packages/soya/_soya.so(+0x8c87c)[0xb6fc487c]
/usr/lib/libpython2.7.so.1.0(PyCFunction_Call+0x14d)[0xb7627c7d]
/usr/lib/libpython2.7.so.1.0(PyObject_Call+0x64)[0xb75eb584]
/usr/lib/libpython2.7.so.1.0(PyEval_CallObjectWithKeywords+0x5b)[0xb768153b]
/usr/lib/libpython2.7.so.1.0(+0x42aeb)[0xb7601aeb]
/usr/lib/libpython2.7.so.1.0(PyObject_Call+0x64)[0xb75eb584]
/usr/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x39e2)[0xb7685542]
/usr/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x87c)[0xb768871c]
/usr/lib/libpython2.7.so.1.0(+0x537bc)[0xb76127bc]
/usr/lib/libpython2.7.so.1.0(PyObject_Call+0x64)[0xb75eb584]
/usr/lib/libpython2.7.so.1.0(+0x3bf70)[0xb75faf70]
/usr/lib/libpython2.7.so.1.0(PyObject_Call+0x64)[0xb75eb584]
/usr/lib/libpython2.7.so.1.0(PyEval_CallObjectWithKeywords+0x5b)[0xb768153b]
/usr/lib/libpython2.7.so.1.0(PyObject_CallObject+0x2b)[0xb75eb51b]
/usr/lib/python2.7/site-packages/soya/_soya.so(+0x38fa3)[0xb6f70fa3]
/usr/lib/libpython2.7.so.1.0(PyCFunction_Call+0x14d)[0xb7627c7d]
/usr/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x4f25)[0xb7686a85]
/usr/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x5d94)[0xb76878f4]
/usr/lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x5d94)[0xb76878f4]
/usr/lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x87c)[0xb768871c]
======= Memory map: ========
08048000-08049000 r-xp 00000000 00:10 13424      /usr/bin/python2.7
08049000-0804a000 r--p 00000000 00:10 13424      /usr/bin/python2.7
0804a000-0804b000 rw-p 00001000 00:10 13424      /usr/bin/python2.7
08ea4000-0a197000 rw-p 00000000 00:00 0          [heap]
b1fdc000-b201b000 r--p 00000000 00:10 17631      /usr/share/games/canta/media/themes/silver/media/fonts/FreeSans.ttf
b20db000-b211a000 r--p 00000000 00:10 17631      /usr/share/games/canta/media/themes/silver/media/fonts/FreeSans.ttf
b221a000-b2262000 r-xp 00000000 00:10 15979      /usr/lib/gstreamer-0.10/libgstcoreelements.so
b2262000-b2263000 ---p 00048000 00:10 15979      /usr/lib/gstreamer-0.10/libgstcoreelements.so
b2263000-b2264000 r--p 00048000 00:10 15979      /usr/lib/gstreamer-0.10/libgstcoreelements.so
b2264000-b2265000 rw-p 00049000 00:10 15979      /usr/lib/gstreamer-0.10/libgstcoreelements.so
b2265000-b22f1000 r-xp 00000000 00:10 8211       /usr/lib/liborc-0.4.so.0.16.0
b22f1000-b22f2000 r--p 0008c000 00:10 8211       /usr/lib/liborc-0.4.so.0.16.0
b22f2000-b22f6000 rw-p 0008d000 00:10 8211       /usr/lib/liborc-0.4.so.0.16.0
b22f6000-b2312000 r-xp 00000000 00:10 8159       /usr/lib/libgstvideo-0.10.so.0.25.0
b2312000-b2313000 r--p 0001b000 00:10 8159       /usr/lib/libgstvideo-0.10.so.0.25.0
b2313000-b2314000 rw-p 0001c000 00:10 8159       /usr/lib/libgstvideo-0.10.so.0.25.0
b2314000-b2334000 r-xp 00000000 00:10 8157       /usr/lib/libgstpbutils-0.10.so.0.25.0
b2334000-b2335000 ---p 00020000 00:10 8157       /usr/lib/libgstpbutils-0.10.so.0.25.0
b2335000-b2336000 r--p 00020000 00:10 8157       /usr/lib/libgstpbutils-0.10.so.0.25.0
b2336000-b2337000 rw-p 00021000 00:10 8157       /usr/lib/libgstpbutils-0.10.so.0.25.0
b2337000-b237a000 r-xp 00000000 00:10 16016      /usr/lib/gstreamer-0.10/libgstplaybin.so
b237a000-b237b000 r--p 00042000 00:10 16016      /usr/lib/gstreamer-0.10/libgstplaybin.so
b237b000-b237c000 rw-p 00043000 00:10 16016      /usr/lib/gstreamer-0.10/libgstplaybin.so
b237c000-b238b000 r-xp 00000000 00:10 8150       /usr/lib/libgstinterfaces-0.10.so.0.25.0
b238b000-b238c000 r--p 0000f000 00:10 8150       /usr/lib/libgstinterfaces-0.10.so.0.25.0
b238c000-b238d000 rw-p 00010000 00:10 8150       /usr/lib/libgstinterfaces-0.10.so.0.25.0
b239d000-b23a5000 r-xp 00000000 00:10 15976      /usr/lib/gstreamer-0.10/libgstautodetect.so
b23a5000-b23a6000 r--p 00007000 00:10 15976      /usr/lib/gstreamer-0.10/libgstautodetect.so
b23a6000-b23a7000 rw-p 00008000 00:10 15976      /usr/lib/gstreamer-0.10/libgstautodetect.so
b23a7000-b23b0000 r-xp 00000000 00:10 15974      /usr/lib/gstreamer-0.10/libgstaudiotestsrc.so
b23b0000-b23b1000 r--p 00008000 00:10 15974      /usr/lib/gstreamer-0.10/libgstaudiotestsrc.so
b23b1000-b23b2000 rw-p 00009000 00:10 15974      /usr/lib/gstreamer-0.10/libgstaudiotestsrc.so
b23b2000-b23c1000 r-xp 00000000 00:10 17730      /usr/lib/python2.7/site-packages/gst-0.10/gst/interfaces.so
b23c1000-b23c2000 r--p 0000e000 00:10 17730      /usr/lib/python2.7/site-packages/gst-0.10/gst/interfaces.so
b23c2000-b23c3000 rw-p 0000f000 00:10 17730      /usr/lib/python2.7/site-packages/gst-0.10/gst/interfaces.so/usr/bin/canta: line 3: 11714 Аварийный останов         python /usr/share/games/canta/run_canta

**Comment by spiderbit** [comment]
maybe one solution for the 0.2 tree could be to remove the save& restart button from this version

**Comment by spiderbit** [comment]
did remove the save & restart button that prevents the crashes
