### ISSUE TITLE
incorrect return from fullscreen mode

### ISSUE THREAD

**Issue by glixx** [spiderbit/canta#14]
sometimes incorrect return from fullscreen mode.

**Comment by spiderbit** [comment]
could be hard to fix, maybe in branch refactoring_2013_05 branch this is fixed.

**Comment by spiderbit** [comment]
I think in 0.3 its fixed... think I wont fix that in 0.2 tree because its basicly one of the biggest points of the 0.3 tree had to rewrite some stuff to get that fixed.

**Comment by spiderbit** [comment]
if somebody gets it fixed with less than 20 lines of code change I maybe add that fix to 0.2 but I dont think so.
