### ISSUE TITLE
Questions instead words

### ISSUE THREAD

**Issue by glixx** [spiderbit/canta#17]
![asd76](https://f.cloud.github.com/assets/2681872/488212/926d9978-b978-11e2-88a1-26c2ef4d2c34.png)

**Comment by spiderbit** [comment]
thats a problem with the song, if you can find lyrics of that song or you hear what they sing there let me know it and I change it ^^

**Comment by spiderbit** [comment]
I think I close that, thats kind of a bug of that song, so you could reasign that bug under the canta-media project but it makes only sense if you find some lyrics to complete that or if you play the song you hear what they are singing a friend of mine who made that song and I dont understand what they are singing there.
